services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: commy:latest
    container_name: commy
    ports:
      - "8085:50505"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/code
    depends_on: []